---
# set path for minishift

- name: "Set path for minishift in {{ ansible_env.HOME }}/.bashrc"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH=$PATH:{{ minishift_dest_dir }}'
    create: yes

- name: "Source {{ ansible_env.HOME }}/.bashrc"
  shell: source {{ ansible_env.HOME }}/.bashrc