---
# set the oc client for the minishift cluster
- name: "Determine the oc client is for profile {{ profile}}"
  shell: "minishift oc-env --profile {{ profile }} | head -1"
  register: oc_client_path

- name: Update the path with the oc client
  shell: "{{ oc_client_path.stdout }}"

- name: "Set path for oc client in {{ ansible_env.HOME }}/.bashrc"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '{{ oc_client_path.stdout }}'
    create: yes

- name: "Source {{ ansible_env.HOME }}/.bashrc"
  shell: source {{ ansible_env.HOME }}/.bashrc

