---
# create/update and add security for containers

- name: "Set the container_config_name to Pipeline containers"
  set_fact:
    container_config_name: "Pipeline containers"

- include: query_setup_cluster.yml template_name={{ item }}
  with_items: "{{ pipeline_bc_templates }}"
  when: pipeline_bc_templates != ""


