---
# create/update jenkins infrastructure master/slaves

- name: "Set the container_config_name to Jenkins Infra"
  set_fact:
    container_config_name: "Jenkins infra"

- include: query_setup_cluster.yml template_name={{ item }}
  with_items: "{{ jenkins_bc_templates }}"
  when: jenkins_bc_templates != ""
